//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-service-SSD_SERVICE_ID_sd_hPcHtfWB2Wb8YomF
import { service as SSD_SERVICE_ID_sd_hPcHtfWB2Wb8YomF } from './sd-services/addCoupon/service';
//CORE_REFERENCE_IMPORT-api-SSD_SERVICE_ID_sd_nHh3CKHPXXm3P2MW
import { api as SSD_SERVICE_ID_sd_nHh3CKHPXXm3P2MW } from './sd-services/addCoupon/api';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-service-SSD_SERVICE_ID_sd_hPcHtfWB2Wb8YomF
SSD_SERVICE_ID_sd_hPcHtfWB2Wb8YomF,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-api-SSD_SERVICE_ID_sd_nHh3CKHPXXm3P2MW
SSD_SERVICE_ID_sd_nHh3CKHPXXm3P2MW,
];
